import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { Country } from "../interface/type";
import styles from "../styles/Home.module.scss";

interface Props {
  countries: Country[];
}

const Home: NextPage<Props> = ({ countries }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {countries.map((country) => {
          <p>{country.name}</p>;
        })}
      </main>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch(`https://restcountries.eu/rest/v2/all`);
  const data = await res.json();
  
  if (!data) {
    return {
      notFound: true,
    };
  }
  return {
    props: {
      countries: { data },
    }
  };
};

export default Home;
